Fix warnings for Elixir 1.4.0
ueberauth/ueberauth_identity pull request #16
Opened 2017-01-16 19:01 UTC by xtian

2017-01-16 19:16 UTC, doomspork requested changes
Thank you @xtian, one question with regards to Travis

2017-01-16 19:16 UTC, doomspork commented on .travis.yml
> +    - elixir: 1.1.0
We don't need to worry about 1.1 anymore but I think we should probably add coverage for 1.3 and 1.2, what do you think?

2017-01-16 19:23 UTC, xtian commented on .travis.yml
> +    - elixir: 1.1.0
@doomspork Most of the projects under the elixir-lang org only test the oldest and newest supported versions. I'm not aware of anything which could fail for 1.3 but not 1.2 or 1.4. Do you know of anything?

2017-01-18 00:10 UTC, xtian commented
@doomspork Any further thoughts on this? As I understand it, breakages relating to the Elixir version could be introduced in two ways:

- a new API/language feature could be used which would break for old versions which didn't support it
- some old API/language feature could be deprecated in a new version (such as the function/variable ambiguity fixed in this PR)

Both cases are covered by testing the oldest and newest supported versions. Anything else would be a semver violation by the Elixir project and should be fixed there.

2017-01-18 17:33 UTC, merged

2017-01-18 17:33 UTC, doomspork commented
Thank you @xtian 👍